### ISSUE TITLE
how to upload on file change

### ISSUE THREAD

**Issue by ahmedash95** [james2doyle/vue-file-upload-component#1]
this component is really amazing but i'm not familiar with javascript . so i wanna know how to start upload on change

**Comment by james2doyle** [comment]
Although Vue is pretty straightforward for people with Javascript experience, it is beyond me for where to start for a beginner. 

I would suggest this series https://laracasts.com/series/learning-vue-step-by-step, but even then, it assumes you already know some javascript.
