### ISSUE TITLE
Adding to a component

### ISSUE THREAD

**Issue by asarmiento** [james2doyle/vue-file-upload-component#14]
Hi, I'm trying to add the library to a component I have in my project. But I have not been able to make it work out these mistakes, I am new to Vue.js.

Here I put the code as I have in my project

I am working on laravel 5.4 and the whole view with components of vue

in bootstrap.js
`Vue.use(require('vue-file-upload-component'));`

in CreateCheck.vue

`<div class="panel-default ">
          <div class="input-group my-file-uploader " >
                     <file-upload
                                            :name="files"
                                            action="/tesoreria/save-check"
                                            :method="PATCH"
                                                 :class="my-file-uploader"></file-upload>
           </div>
</div>`

` import FileUpload from 'vue-file-upload-component';
    export default {
        props: ['title','url','banks'],
        components: {vSelect, FileUpload},
        data () {
             return   {
                 data: {
                     number: '',
                     bank: '',
                     name: '',
                     balance: '',
                     type: '',
                     files: [],
                 },
                 errors: {
                     number: '',
                     bank: '',
                     name: '',
                     balance: '',
                     detail: '',
                     type: '',
                 },
                 option: [
                     {'value':'chuech','label':'Gastos de Iglesia'},
                     {'value':'local_field','label':'Reporte al Campo Local'}
                 ],
             }
         },`

**Comment by james2doyle** [comment]
This library is for Vue 1. Is that possibly the issue?

**Comment by asarmiento** [comment]
Oh ya comprendo, 
Oh I see,

**Comment by james2doyle** [comment]
It probably won't work. You will need to use another library.

**Comment by asarmiento** [comment]
Gracias, 
Thanks
