### ISSUE TITLE
How can I import this in Vue?

### ISSUE THREAD

**Issue by matiastucci** [james2doyle/vue-file-upload-component#6]
I installed it using `npm` and I'm doing `import FileUploadComponent from 'vue-file-upload-component';` but I get `Vue is not defined`

**Comment by StevenYuysy** [comment]
Do you import the Vue? If you are using vue file in ES6, try

```
import Vue form 'vue'
```

**Comment by matiastucci** [comment]
Yep, I already tried that

**Comment by StevenYuysy** [comment]
You can try it in this way:

``` JavaScript
    Vue.component('file-upload', function(resolve) {
            require(['path-to/vue.file-upload.js','path-to/vue.pretty-bytes.js'], resolve);
        });
```

It work in my current project.

**Comment by woshihaoren** [comment]
@StevenYuysy 
Uncaught ReferenceError: Vue is not defined
It isn't OK

**Comment by StevenYuysy** [comment]
@woshihaoren 
Did you write it in a Vue file? If you did, you should not only import Vue in root component but also import Vue again in current component.
Show me the code plz
